/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.viadeo.data.bean;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MailReport extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MailReport\",\"namespace\":\"com.viadeo.data.bean\",\"fields\":[{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"email\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"reason\",\"type\":\"string\"},{\"name\":\"memberId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"campaign\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"created\",\"type\":\"long\"},{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lang\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"premium\",\"type\":\"boolean\"},{\"name\":\"visits\",\"type\":\"int\"},{\"name\":\"adId\",\"type\":\"int\"},{\"name\":\"monthly\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence status;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public java.lang.CharSequence reason;
  @Deprecated public java.lang.CharSequence memberId;
  @Deprecated public java.lang.CharSequence campaign;
  @Deprecated public long created;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence lang;
  @Deprecated public boolean premium;
  @Deprecated public int visits;
  @Deprecated public int adId;
  @Deprecated public boolean monthly;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public MailReport() {}

  /**
   * All-args constructor.
   */
  public MailReport(java.lang.CharSequence status, java.lang.CharSequence email, java.lang.CharSequence reason, java.lang.CharSequence memberId, java.lang.CharSequence campaign, java.lang.Long created, java.lang.CharSequence id, java.lang.CharSequence lang, java.lang.Boolean premium, java.lang.Integer visits, java.lang.Integer adId, java.lang.Boolean monthly) {
    this.status = status;
    this.email = email;
    this.reason = reason;
    this.memberId = memberId;
    this.campaign = campaign;
    this.created = created;
    this.id = id;
    this.lang = lang;
    this.premium = premium;
    this.visits = visits;
    this.adId = adId;
    this.monthly = monthly;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return status;
    case 1: return email;
    case 2: return reason;
    case 3: return memberId;
    case 4: return campaign;
    case 5: return created;
    case 6: return id;
    case 7: return lang;
    case 8: return premium;
    case 9: return visits;
    case 10: return adId;
    case 11: return monthly;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: status = (java.lang.CharSequence)value$; break;
    case 1: email = (java.lang.CharSequence)value$; break;
    case 2: reason = (java.lang.CharSequence)value$; break;
    case 3: memberId = (java.lang.CharSequence)value$; break;
    case 4: campaign = (java.lang.CharSequence)value$; break;
    case 5: created = (java.lang.Long)value$; break;
    case 6: id = (java.lang.CharSequence)value$; break;
    case 7: lang = (java.lang.CharSequence)value$; break;
    case 8: premium = (java.lang.Boolean)value$; break;
    case 9: visits = (java.lang.Integer)value$; break;
    case 10: adId = (java.lang.Integer)value$; break;
    case 11: monthly = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'reason' field.
   */
  public java.lang.CharSequence getReason() {
    return reason;
  }

  /**
   * Sets the value of the 'reason' field.
   * @param value the value to set.
   */
  public void setReason(java.lang.CharSequence value) {
    this.reason = value;
  }

  /**
   * Gets the value of the 'memberId' field.
   */
  public java.lang.CharSequence getMemberId() {
    return memberId;
  }

  /**
   * Sets the value of the 'memberId' field.
   * @param value the value to set.
   */
  public void setMemberId(java.lang.CharSequence value) {
    this.memberId = value;
  }

  /**
   * Gets the value of the 'campaign' field.
   */
  public java.lang.CharSequence getCampaign() {
    return campaign;
  }

  /**
   * Sets the value of the 'campaign' field.
   * @param value the value to set.
   */
  public void setCampaign(java.lang.CharSequence value) {
    this.campaign = value;
  }

  /**
   * Gets the value of the 'created' field.
   */
  public java.lang.Long getCreated() {
    return created;
  }

  /**
   * Sets the value of the 'created' field.
   * @param value the value to set.
   */
  public void setCreated(java.lang.Long value) {
    this.created = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'lang' field.
   */
  public java.lang.CharSequence getLang() {
    return lang;
  }

  /**
   * Sets the value of the 'lang' field.
   * @param value the value to set.
   */
  public void setLang(java.lang.CharSequence value) {
    this.lang = value;
  }

  /**
   * Gets the value of the 'premium' field.
   */
  public java.lang.Boolean getPremium() {
    return premium;
  }

  /**
   * Sets the value of the 'premium' field.
   * @param value the value to set.
   */
  public void setPremium(java.lang.Boolean value) {
    this.premium = value;
  }

  /**
   * Gets the value of the 'visits' field.
   */
  public java.lang.Integer getVisits() {
    return visits;
  }

  /**
   * Sets the value of the 'visits' field.
   * @param value the value to set.
   */
  public void setVisits(java.lang.Integer value) {
    this.visits = value;
  }

  /**
   * Gets the value of the 'adId' field.
   */
  public java.lang.Integer getAdId() {
    return adId;
  }

  /**
   * Sets the value of the 'adId' field.
   * @param value the value to set.
   */
  public void setAdId(java.lang.Integer value) {
    this.adId = value;
  }

  /**
   * Gets the value of the 'monthly' field.
   */
  public java.lang.Boolean getMonthly() {
    return monthly;
  }

  /**
   * Sets the value of the 'monthly' field.
   * @param value the value to set.
   */
  public void setMonthly(java.lang.Boolean value) {
    this.monthly = value;
  }

  /** Creates a new MailReport RecordBuilder */
  public static com.viadeo.data.bean.MailReport.Builder newBuilder() {
    return new com.viadeo.data.bean.MailReport.Builder();
  }
  
  /** Creates a new MailReport RecordBuilder by copying an existing Builder */
  public static com.viadeo.data.bean.MailReport.Builder newBuilder(com.viadeo.data.bean.MailReport.Builder other) {
    return new com.viadeo.data.bean.MailReport.Builder(other);
  }
  
  /** Creates a new MailReport RecordBuilder by copying an existing MailReport instance */
  public static com.viadeo.data.bean.MailReport.Builder newBuilder(com.viadeo.data.bean.MailReport other) {
    return new com.viadeo.data.bean.MailReport.Builder(other);
  }
  
  /**
   * RecordBuilder for MailReport instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MailReport>
    implements org.apache.avro.data.RecordBuilder<MailReport> {

    private java.lang.CharSequence status;
    private java.lang.CharSequence email;
    private java.lang.CharSequence reason;
    private java.lang.CharSequence memberId;
    private java.lang.CharSequence campaign;
    private long created;
    private java.lang.CharSequence id;
    private java.lang.CharSequence lang;
    private boolean premium;
    private int visits;
    private int adId;
    private boolean monthly;

    /** Creates a new Builder */
    private Builder() {
      super(com.viadeo.data.bean.MailReport.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.viadeo.data.bean.MailReport.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.memberId)) {
        this.memberId = data().deepCopy(fields()[3].schema(), other.memberId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.campaign)) {
        this.campaign = data().deepCopy(fields()[4].schema(), other.campaign);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.created)) {
        this.created = data().deepCopy(fields()[5].schema(), other.created);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.id)) {
        this.id = data().deepCopy(fields()[6].schema(), other.id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lang)) {
        this.lang = data().deepCopy(fields()[7].schema(), other.lang);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.premium)) {
        this.premium = data().deepCopy(fields()[8].schema(), other.premium);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.visits)) {
        this.visits = data().deepCopy(fields()[9].schema(), other.visits);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.adId)) {
        this.adId = data().deepCopy(fields()[10].schema(), other.adId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.monthly)) {
        this.monthly = data().deepCopy(fields()[11].schema(), other.monthly);
        fieldSetFlags()[11] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MailReport instance */
    private Builder(com.viadeo.data.bean.MailReport other) {
            super(com.viadeo.data.bean.MailReport.SCHEMA$);
      if (isValidValue(fields()[0], other.status)) {
        this.status = data().deepCopy(fields()[0].schema(), other.status);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email)) {
        this.email = data().deepCopy(fields()[1].schema(), other.email);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.reason)) {
        this.reason = data().deepCopy(fields()[2].schema(), other.reason);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.memberId)) {
        this.memberId = data().deepCopy(fields()[3].schema(), other.memberId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.campaign)) {
        this.campaign = data().deepCopy(fields()[4].schema(), other.campaign);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.created)) {
        this.created = data().deepCopy(fields()[5].schema(), other.created);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.id)) {
        this.id = data().deepCopy(fields()[6].schema(), other.id);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.lang)) {
        this.lang = data().deepCopy(fields()[7].schema(), other.lang);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.premium)) {
        this.premium = data().deepCopy(fields()[8].schema(), other.premium);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.visits)) {
        this.visits = data().deepCopy(fields()[9].schema(), other.visits);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.adId)) {
        this.adId = data().deepCopy(fields()[10].schema(), other.adId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.monthly)) {
        this.monthly = data().deepCopy(fields()[11].schema(), other.monthly);
        fieldSetFlags()[11] = true;
      }
    }

    /** Gets the value of the 'status' field */
    public java.lang.CharSequence getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public com.viadeo.data.bean.MailReport.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.status = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'status' field */
    public com.viadeo.data.bean.MailReport.Builder clearStatus() {
      status = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'email' field */
    public java.lang.CharSequence getEmail() {
      return email;
    }
    
    /** Sets the value of the 'email' field */
    public com.viadeo.data.bean.MailReport.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'email' field has been set */
    public boolean hasEmail() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'email' field */
    public com.viadeo.data.bean.MailReport.Builder clearEmail() {
      email = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'reason' field */
    public java.lang.CharSequence getReason() {
      return reason;
    }
    
    /** Sets the value of the 'reason' field */
    public com.viadeo.data.bean.MailReport.Builder setReason(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.reason = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'reason' field has been set */
    public boolean hasReason() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'reason' field */
    public com.viadeo.data.bean.MailReport.Builder clearReason() {
      reason = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'memberId' field */
    public java.lang.CharSequence getMemberId() {
      return memberId;
    }
    
    /** Sets the value of the 'memberId' field */
    public com.viadeo.data.bean.MailReport.Builder setMemberId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.memberId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'memberId' field has been set */
    public boolean hasMemberId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'memberId' field */
    public com.viadeo.data.bean.MailReport.Builder clearMemberId() {
      memberId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'campaign' field */
    public java.lang.CharSequence getCampaign() {
      return campaign;
    }
    
    /** Sets the value of the 'campaign' field */
    public com.viadeo.data.bean.MailReport.Builder setCampaign(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.campaign = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'campaign' field has been set */
    public boolean hasCampaign() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'campaign' field */
    public com.viadeo.data.bean.MailReport.Builder clearCampaign() {
      campaign = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'created' field */
    public java.lang.Long getCreated() {
      return created;
    }
    
    /** Sets the value of the 'created' field */
    public com.viadeo.data.bean.MailReport.Builder setCreated(long value) {
      validate(fields()[5], value);
      this.created = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'created' field has been set */
    public boolean hasCreated() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'created' field */
    public com.viadeo.data.bean.MailReport.Builder clearCreated() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public com.viadeo.data.bean.MailReport.Builder setId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.id = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'id' field */
    public com.viadeo.data.bean.MailReport.Builder clearId() {
      id = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'lang' field */
    public java.lang.CharSequence getLang() {
      return lang;
    }
    
    /** Sets the value of the 'lang' field */
    public com.viadeo.data.bean.MailReport.Builder setLang(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.lang = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'lang' field has been set */
    public boolean hasLang() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'lang' field */
    public com.viadeo.data.bean.MailReport.Builder clearLang() {
      lang = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'premium' field */
    public java.lang.Boolean getPremium() {
      return premium;
    }
    
    /** Sets the value of the 'premium' field */
    public com.viadeo.data.bean.MailReport.Builder setPremium(boolean value) {
      validate(fields()[8], value);
      this.premium = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'premium' field has been set */
    public boolean hasPremium() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'premium' field */
    public com.viadeo.data.bean.MailReport.Builder clearPremium() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'visits' field */
    public java.lang.Integer getVisits() {
      return visits;
    }
    
    /** Sets the value of the 'visits' field */
    public com.viadeo.data.bean.MailReport.Builder setVisits(int value) {
      validate(fields()[9], value);
      this.visits = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'visits' field has been set */
    public boolean hasVisits() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'visits' field */
    public com.viadeo.data.bean.MailReport.Builder clearVisits() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'adId' field */
    public java.lang.Integer getAdId() {
      return adId;
    }
    
    /** Sets the value of the 'adId' field */
    public com.viadeo.data.bean.MailReport.Builder setAdId(int value) {
      validate(fields()[10], value);
      this.adId = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'adId' field has been set */
    public boolean hasAdId() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'adId' field */
    public com.viadeo.data.bean.MailReport.Builder clearAdId() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'monthly' field */
    public java.lang.Boolean getMonthly() {
      return monthly;
    }
    
    /** Sets the value of the 'monthly' field */
    public com.viadeo.data.bean.MailReport.Builder setMonthly(boolean value) {
      validate(fields()[11], value);
      this.monthly = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'monthly' field has been set */
    public boolean hasMonthly() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'monthly' field */
    public com.viadeo.data.bean.MailReport.Builder clearMonthly() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    public MailReport build() {
      try {
        MailReport record = new MailReport();
        record.status = fieldSetFlags()[0] ? this.status : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email = fieldSetFlags()[1] ? this.email : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.reason = fieldSetFlags()[2] ? this.reason : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.memberId = fieldSetFlags()[3] ? this.memberId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.campaign = fieldSetFlags()[4] ? this.campaign : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.created = fieldSetFlags()[5] ? this.created : (java.lang.Long) defaultValue(fields()[5]);
        record.id = fieldSetFlags()[6] ? this.id : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.lang = fieldSetFlags()[7] ? this.lang : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.premium = fieldSetFlags()[8] ? this.premium : (java.lang.Boolean) defaultValue(fields()[8]);
        record.visits = fieldSetFlags()[9] ? this.visits : (java.lang.Integer) defaultValue(fields()[9]);
        record.adId = fieldSetFlags()[10] ? this.adId : (java.lang.Integer) defaultValue(fields()[10]);
        record.monthly = fieldSetFlags()[11] ? this.monthly : (java.lang.Boolean) defaultValue(fields()[11]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
